class CredentialsError(Exception): ...
class PayloadChecksumError(Exception): ...
class HeaderChecksumError(Exception): ...
class BinaryError(Exception): ...
class UnableToSendToRecycleBin(Exception): ...
