from .entry import Entry
from .pykeepass import PyKeePass

class Attachment:
    def __init__(
        self,
        element: object = None,
        kp: PyKeePass | None = None,
        id: int | None = None,
        filename: str | None = None,
    ) -> None: ...
    @property
    def id(self) -> int: ...
    @id.setter
    def id(self, id: int) -> None: ...
    @property
    def filename(self) -> str: ...
    @filename.setter
    def filename(self, filename: str) -> None: ...
    @property
    def entry(self) -> Entry: ...
    @property
    def binary(self) -> bytes: ...
    @property
    def data(self) -> bytes: ...
    def delete(self) -> None: ...
