# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
# adapted from https://github.com/kjanat/notso-glb/blob/e9dec45b481d09651034c54ddc5913589b7156b9/.github/workflows/pr-test-comment.yml
---
name: PR Test Comment
on: { pull_request_target: { types: [opened, synchronize, reopened, closed] } }
permissions: { contents: read, issues: write, pull-requests: write }
jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.14
      CLI_NAME: kp2bw
      CLI_EXAMPLES: |
        # Show version
        {cmd} --version
        # Migrate KeePass DB (interactive password prompts)
        {cmd} vault.kdbx
        # Non-interactive with env vars
        KP2BW_KEEPASS_PASSWORD=kppass KP2BW_BITWARDEN_PASSWORD=bwpass {cmd} vault.kdbx -y
    steps:
      - name: Check out PR comment script
        uses: actions/checkout@v7.0.0
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          sparse-checkout: scripts/pr-comment.mjs
          sparse-checkout-cone-mode: false
          persist-credentials: false

      - name: Create or update PR comment
        uses: actions/github-script@v9
        with:
          script: |
            const { default: comment } = await import("${{ github.workspace }}/scripts/pr-comment.mjs");
            return await comment({ core, context, github });
